In [1]:
import os
import re

from dotenv import load_dotenv
from google.cloud import bigquery
import pandas as pd

C:\Users\A200162055\Miniconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
HTTP_PROXY = 'http://sia-lb.telekom.de:8080'
HTTPS_PROXY = 'http://sia-lb.telekom.de:8080'

os.environ['http_proxy'] = HTTP_PROXY
os.environ['https_proxy'] = HTTPS_PROXY

activities_url = 'https://www.strava.com/api/v3/athlete/activities'
auth_url = 'https://www.strava.com/oauth/token'

load_dotenv()

CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')
REFRESH_TOKEN = os.getenv('REFRESH_TOKEN')
GRANT_TYPE = os.getenv('GRANT_TYPE')

In [3]:
from src.strava.strava_utils import fetch_all_activities, get_access_token

access_token = get_access_token(CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, GRANT_TYPE)

activities = fetch_all_activities(access_token)
df_activities = pd.json_normalize(activities)

print('The length of all activies is: ', len(df_activities))

C:\Users\A200162055\Miniconda3\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sia-lb.telekom.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

The length of all activies is:  193

In [4]:
df_activities

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Hill Intervals,7502.8,2402,2405,230.0,Run,Run,0.0,15309238742,...,garmin_ping_465048251379,False,0,0,False,133094316,1,a15309238742,kcluHkq}j@DMn@yAJ]|@{B?i@Em@QwAIkB?GHW@Om@kIe@...,2
1,2,Easy Run,10090.9,3532,3579,83.0,Run,Run,0.0,15298830273,...,garmin_ping_464720550858,False,0,0,False,133094316,1,a15298830273,qeluHwm|j@NzBB`CIhAIdBKp@QnCWfB]~@s@bCk@bCOz@K...,2
2,2,First 100k,100376.0,14606,15953,1206.0,Ride,Ride,10.0,15287917307,...,garmin_ping_464391433871,False,11,0,False,133094316,1,a15287917307,waluH_q|j@rN`EnCbJoi@n}AqPjjA{L`g@cGfBkJqKeE}@...,2
3,2,Tempo Run,12146.8,3056,3059,125.0,Run,Run,0.0,15272351610,...,garmin_ping_463957509479,False,0,0,False,133094316,1,a15272351610,qeluHim|j@JhFAv@ObCIj@[lEKn@]~@Ux@[z@Qr@YnAYpB...,2
4,2,Basic Run,8563.2,2643,2643,78.0,Run,Run,0.0,15252182113,...,garmin_ping_463303625408,False,0,0,False,133094316,1,a15252182113,ywluHoq|j@FpAHp@HpBFv@ELMDI?e@QOOa@i@O]c@q@sAs...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,2,Saturday Run,7772.5,2512,2531,61.9,Run,Run,0.0,12748074315,...,shealth64f609a4-1b3e-4a03-ae7c-08017cbd729d.tcx,False,0,0,False,133094316,1,a12748074315,aeluHek|j@BVCj@@nCOdBKj@Ej@Ax@EpA?h@CZKd@c@jAO...,2
189,2,Saturday Run,15349.0,4309,4348,97.8,Run,Run,0.0,12692532615,...,shealth87feca60-6d66-49c9-b38f-bf265c219738.tcx,False,0,0,False,133094316,1,a12692532615,_eluHcn|j@HpEC~@SfCYlBKnA_@xBa@dB_A~Be@bBMr@Op...,2
190,2,Short Ride,9819.9,1808,1808,77.9,Ride,Ride,10.0,12669613985,...,shealtha8299e3a-bd8c-4702-b0e1-32aebe4cfa90.tcx,False,0,0,False,133094316,1,a12669613985,geluHwm|j@CT?d@FZCx@D|@KhBAhACLAb@Qz@YpEW~@Uj@...,2
191,2,Recovery Run,8681.4,2906,2916,72.3,Run,Run,0.0,12644836289,...,stripped_shealthc039a055-7f09-4453-b1e6-b8b6ab...,False,0,0,False,133094316,1,a12644836289,geluHsl|j@D~@AdCUhESxAObCQfASv@a@lAc@z@Mj@Mr@G...,2
192,2,Lunch Run,6000.2,1668,1681,41.4,Run,Run,0.0,12635874694,...,stripped_shealth8813d230-d336-41c8-a24b-a96ebe...,False,0,0,False,133094316,1,a12635874694,geluHuk|j@BvBIbEYjCI`BOzAGZg@dAOl@i@xAKb@]bCIx...,2

In [5]:
df_activities.columns = [
    re.sub(r'[^a-zA-Z0-9_]', '_', col) for col in df_activities.columns
]

In [6]:
df_activities

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete_id,athlete_resource_state,map_id,map_summary_polyline,map_resource_state
0,2,Hill Intervals,7502.8,2402,2405,230.0,Run,Run,0.0,15309238742,...,garmin_ping_465048251379,False,0,0,False,133094316,1,a15309238742,kcluHkq}j@DMn@yAJ]|@{B?i@Em@QwAIkB?GHW@Om@kIe@...,2
1,2,Easy Run,10090.9,3532,3579,83.0,Run,Run,0.0,15298830273,...,garmin_ping_464720550858,False,0,0,False,133094316,1,a15298830273,qeluHwm|j@NzBB`CIhAIdBKp@QnCWfB]~@s@bCk@bCOz@K...,2
2,2,First 100k,100376.0,14606,15953,1206.0,Ride,Ride,10.0,15287917307,...,garmin_ping_464391433871,False,11,0,False,133094316,1,a15287917307,waluH_q|j@rN`EnCbJoi@n}AqPjjA{L`g@cGfBkJqKeE}@...,2
3,2,Tempo Run,12146.8,3056,3059,125.0,Run,Run,0.0,15272351610,...,garmin_ping_463957509479,False,0,0,False,133094316,1,a15272351610,qeluHim|j@JhFAv@ObCIj@[lEKn@]~@Ux@[z@Qr@YnAYpB...,2
4,2,Basic Run,8563.2,2643,2643,78.0,Run,Run,0.0,15252182113,...,garmin_ping_463303625408,False,0,0,False,133094316,1,a15252182113,ywluHoq|j@FpAHp@HpBFv@ELMDI?e@QOOa@i@O]c@q@sAs...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,2,Saturday Run,7772.5,2512,2531,61.9,Run,Run,0.0,12748074315,...,shealth64f609a4-1b3e-4a03-ae7c-08017cbd729d.tcx,False,0,0,False,133094316,1,a12748074315,aeluHek|j@BVCj@@nCOdBKj@Ej@Ax@EpA?h@CZKd@c@jAO...,2
189,2,Saturday Run,15349.0,4309,4348,97.8,Run,Run,0.0,12692532615,...,shealth87feca60-6d66-49c9-b38f-bf265c219738.tcx,False,0,0,False,133094316,1,a12692532615,_eluHcn|j@HpEC~@SfCYlBKnA_@xBa@dB_A~Be@bBMr@Op...,2
190,2,Short Ride,9819.9,1808,1808,77.9,Ride,Ride,10.0,12669613985,...,shealtha8299e3a-bd8c-4702-b0e1-32aebe4cfa90.tcx,False,0,0,False,133094316,1,a12669613985,geluHwm|j@CT?d@FZCx@D|@KhBAhACLAb@Qz@YpEW~@Uj@...,2
191,2,Recovery Run,8681.4,2906,2916,72.3,Run,Run,0.0,12644836289,...,stripped_shealthc039a055-7f09-4453-b1e6-b8b6ab...,False,0,0,False,133094316,1,a12644836289,geluHsl|j@D~@AdCUhESxAObCQfASv@a@lAc@z@Mj@Mr@G...,2
192,2,Lunch Run,6000.2,1668,1681,41.4,Run,Run,0.0,12635874694,...,stripped_shealth8813d230-d336-41c8-a24b-a96ebe...,False,0,0,False,133094316,1,a12635874694,geluHuk|j@BvBIbEYjCI`BOzAGZg@dAOl@i@xAKb@]bCIx...,2

In [7]:
PROJECT_ID = 'athlete-dashboard-467718'
DATASET_ID = 'strava_data_overview'
TABLE_ID = 'activities_strava'
# client = bigquery.Client(project=PROJECT_ID)
client = bigquery.Client.from_service_account_json(
    'C:/Users/A200162055/Downloads/athlete-dashboard-467718-d5f31b294e6f.json',
    project='athlete-dashboard-467718',
)

In [8]:
job_config = bigquery.LoadJobConfig(write_disposition='WRITE_TRUNCATE')

full_table_id = f'{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}'

client.load_table_from_dataframe(
    df_activities, full_table_id, job_config=job_config
).result()

C:\Users\A200162055\Miniconda3\lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(
C:\Users\A200162055\Miniconda3\lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:551: UserWarning: Could not determine the type of columns: location_city, location_state, location_country
  warnings.warn(msg)

LoadJob<project=athlete-dashboard-467718, location=europe-west3, id=f4c31259-1257-40bf-a328-c37b884ba8d6>