In [3]:
import os

from google.cloud import bigquery

HTTP_PROXY = 'http://sia-lb.telekom.de:8080'
HTTPS_PROXY = 'http://sia-lb.telekom.de:8080'

os.environ['http_proxy'] = HTTP_PROXY
os.environ['https_proxy'] = HTTPS_PROXY

# --- 1. Initialize BigQuery client ---
PROJECT_ID = 'athlete-dashboard-467718'
DATASET_ID = 'strava_data_overview'
TABLE_ID = 'strava_data_test'
# client = bigquery.Client(project=PROJECT_ID)
client = bigquery.Client.from_service_account_json(
    'C:/Users/A200162055/Downloads/athlete-dashboard-467718-d5f31b294e6f.json',
    project='athlete-dashboard-467718',
)
print('BigQuery verbunden!')

full_table_id = f'{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}'

# --- 4. Prüfen, ob Tabelle existiert ---
table = client.get_table(full_table_id)
print(f'ℹ️ Tabelle gefunden: {full_table_id}')
print(f'Spalten: {[schema.name for schema in table.schema]}')
print(f'Zeilen: {table.num_rows}')

# --- 5. Kleine Abfrage, um Daten zu testen ---
query = f'SELECT * FROM `{full_table_id}`'
print('🔹 Starte Abfrage:', query)

job = client.query(query)
df = job.result().to_dataframe()  # Ergebnisse in Pandas DataFrame

print('✅ Abfrage abgeschlossen, erste Zeilen:')
df

BigQuery verbunden!
ℹ️ Tabelle gefunden: athlete-dashboard-467718.strava_data_overview.strava_data_test
Spalten: ['Column', 'Dtype', 'Unique Count', 'Null Count', 'Missing %', 'Example Value', 'Description']
Geschätzte Zeilen: 58
🔹 Starte Abfrage: SELECT * FROM `athlete-dashboard-467718.strava_data_overview.strava_data_test`
✅ Abfrage abgeschlossen, erste Zeilen:

C:\Users\A200162055\Miniconda3\lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,Column,Dtype,Unique Count,Null Count,Missing %,Example Value,Description
0,trainer,bool,2,0,0.00,False,TODO: Add description for each column
1,commute,bool,1,0,0.00,False,TODO: Add description for each column
2,manual,bool,1,0,0.00,False,TODO: Add description for each column
3,private,bool,1,0,0.00,False,TODO: Add description for each column
4,flagged,bool,1,0,0.00,False,TODO: Add description for each column
5,has_heartrate,bool,2,0,0.00,True,TODO: Add description for each column
6,heartrate_opt_out,bool,1,0,0.00,False,TODO: Add description for each column
7,display_hide_heartrate_option,bool,2,0,0.00,True,TODO: Add description for each column
8,from_accepted_tag,bool,1,0,0.00,False,TODO: Add description for each column
9,has_kudoed,bool,1,0,0.00,False,TODO: Add description for each column
10,distance,float64,191,0,0.00,7502.8,TODO: Add description for each column
11,total_elevation_gain,float64,126,0,0.00,230.0,TODO: Add description for each column
12,utc_offset,float64,2,0,0.00,7200.0,TODO: Add description for each column
13,average_speed,float64,186,0,0.00,3.124,TODO: Add description for each column
14,max_speed,float64,158,0,0.00,4.7,TODO: Add description for each column
15,elev_high,float64,98,0,0.00,114.6,TODO: Add description for each column
16,elev_low,float64,149,0,0.00,76.2,TODO: Add description for each column
17,resource_state,int64,1,0,0.00,2,TODO: Add description for each column
18,moving_time,int64,188,0,0.00,2402,TODO: Add description for each column
19,elapsed_time,int64,189,0,0.00,2405,TODO: Add description for each column
20,id,int64,193,0,0.00,15309238742,TODO: Add description for each column
21,achievement_count,int64,25,0,0.00,0,TODO: Add description for each column
22,kudos_count,int64,5,0,0.00,0,TODO: Add description for each column
23,comment_count,int64,3,0,0.00,0,TODO: Add description for each column
24,athlete_count,int64,2,0,0.00,1,TODO: Add description for each column
25,photo_count,int64,1,0,0.00,0,TODO: Add description for each column
26,upload_id,int64,193,0,0.00,16349023789,TODO: Add description for each column
27,pr_count,int64,18,0,0.00,0,TODO: Add description for each column
28,total_photo_count,int64,2,0,0.00,0,TODO: Add description for each column
29,athlete.id,int64,1,0,0.00,133094316,TODO: Add description for each column
30,athlete.resource_state,int64,1,0,0.00,1,TODO: Add description for each column
31,map.resource_state,int64,1,0,0.00,2,TODO: Add description for each column
32,name,object,67,0,0.00,Hill Intervals,TODO: Add description for each column
33,type,object,2,0,0.00,Run,TODO: Add description for each column
34,sport_type,object,2,0,0.00,Run,TODO: Add description for each column
35,start_date,object,193,0,0.00,2025-08-01T14:16:48Z,TODO: Add description for each column
36,start_date_local,object,193,0,0.00,2025-08-01T16:16:48Z,TODO: Add description for each column
37,timezone,object,3,0,0.00,(GMT+01:00) Europe/Berlin,TODO: Add description for each column
38,visibility,object,1,0,0.00,everyone,TODO: Add description for each column
39,start_latlng,object,193,0,0.00,"[50.858947, 7.197307]",TODO: Add description for each column
40,end_latlng,object,193,0,0.00,"[50.858818, 7.197319]",TODO: Add description for each column
41,upload_id_str,object,193,0,0.00,16349023789,TODO: Add description for each column
42,external_id,object,193,0,0.00,garmin_ping_465048251379,TODO: Add description for each column
43,map.id,object,193,0,0.00,a15309238742,TODO: Add description for each column
44,map.summary_polyline,object,193,0,0.00,kcluHkq}j@DMn@yAJ]|@{B?i@Em@QwAIkB?GHW@Om@kIe@...,TODO: Add description for each column
45,average_heartrate,float64,150,2,1.04,131.2,TODO: Add description for each column
46,max_heartrate,float64,52,2,1.04,175.0,TODO: Add description for each column
47,gear_id,object,5,2,1.04,g20984891,TODO: Add description for each column
48,workout_type,float64,3,6,3.11,0.0,TODO: Add description for each column
49,average_cadence,float64,63,61,31.61,85.5,TODO: Add description for each column
50,average_watts,float64,114,70,36.27,320.0,TODO: Add description for each column
51,max_watts,float64,95,70,36.27,587.0,TODO: Add description for each column
52,weighted_average_watts,float64,72,70,36.27,369.0,TODO: Add description for each column
53,kilojoules,float64,120,70,36.27,769.9,TODO: Add description for each column
54,device_watts,object,1,70,36.27,True,TODO: Add description for each column
55,location_city,object,0,193,100.00,None,TODO: Add description for each column
56,location_state,object,0,193,100.00,None,TODO: Add description for each column
57,location_country,object,0,193,100.00,None,TODO: Add description for each column

In [6]:
df.loc[df['Column'] == 'distance', 'Description'] = 'Distance of Activity in meters'

In [7]:
df

,Column,Dtype,Unique Count,Null Count,Missing %,Example Value,Description
0,trainer,bool,2,0,0.00,False,TODO: Add description for each column
1,commute,bool,1,0,0.00,False,TODO: Add description for each column
2,manual,bool,1,0,0.00,False,TODO: Add description for each column
3,private,bool,1,0,0.00,False,TODO: Add description for each column
4,flagged,bool,1,0,0.00,False,TODO: Add description for each column
5,has_heartrate,bool,2,0,0.00,True,TODO: Add description for each column
6,heartrate_opt_out,bool,1,0,0.00,False,TODO: Add description for each column
7,display_hide_heartrate_option,bool,2,0,0.00,True,TODO: Add description for each column
8,from_accepted_tag,bool,1,0,0.00,False,TODO: Add description for each column
9,has_kudoed,bool,1,0,0.00,False,TODO: Add description for each column
10,distance,float64,191,0,0.00,7502.8,Distance of Activity in meters
11,total_elevation_gain,float64,126,0,0.00,230.0,TODO: Add description for each column
12,utc_offset,float64,2,0,0.00,7200.0,TODO: Add description for each column
13,average_speed,float64,186,0,0.00,3.124,TODO: Add description for each column
14,max_speed,float64,158,0,0.00,4.7,TODO: Add description for each column
15,elev_high,float64,98,0,0.00,114.6,TODO: Add description for each column
16,elev_low,float64,149,0,0.00,76.2,TODO: Add description for each column
17,resource_state,int64,1,0,0.00,2,TODO: Add description for each column
18,moving_time,int64,188,0,0.00,2402,TODO: Add description for each column
19,elapsed_time,int64,189,0,0.00,2405,TODO: Add description for each column
20,id,int64,193,0,0.00,15309238742,TODO: Add description for each column
21,achievement_count,int64,25,0,0.00,0,TODO: Add description for each column
22,kudos_count,int64,5,0,0.00,0,TODO: Add description for each column
23,comment_count,int64,3,0,0.00,0,TODO: Add description for each column
24,athlete_count,int64,2,0,0.00,1,TODO: Add description for each column
25,photo_count,int64,1,0,0.00,0,TODO: Add description for each column
26,upload_id,int64,193,0,0.00,16349023789,TODO: Add description for each column
27,pr_count,int64,18,0,0.00,0,TODO: Add description for each column
28,total_photo_count,int64,2,0,0.00,0,TODO: Add description for each column
29,athlete.id,int64,1,0,0.00,133094316,TODO: Add description for each column
30,athlete.resource_state,int64,1,0,0.00,1,TODO: Add description for each column
31,map.resource_state,int64,1,0,0.00,2,TODO: Add description for each column
32,name,object,67,0,0.00,Hill Intervals,TODO: Add description for each column
33,type,object,2,0,0.00,Run,TODO: Add description for each column
34,sport_type,object,2,0,0.00,Run,TODO: Add description for each column
35,start_date,object,193,0,0.00,2025-08-01T14:16:48Z,TODO: Add description for each column
36,start_date_local,object,193,0,0.00,2025-08-01T16:16:48Z,TODO: Add description for each column
37,timezone,object,3,0,0.00,(GMT+01:00) Europe/Berlin,TODO: Add description for each column
38,visibility,object,1,0,0.00,everyone,TODO: Add description for each column
39,start_latlng,object,193,0,0.00,"[50.858947, 7.197307]",TODO: Add description for each column
40,end_latlng,object,193,0,0.00,"[50.858818, 7.197319]",TODO: Add description for each column
41,upload_id_str,object,193,0,0.00,16349023789,TODO: Add description for each column
42,external_id,object,193,0,0.00,garmin_ping_465048251379,TODO: Add description for each column
43,map.id,object,193,0,0.00,a15309238742,TODO: Add description for each column
44,map.summary_polyline,object,193,0,0.00,kcluHkq}j@DMn@yAJ]|@{B?i@Em@QwAIkB?GHW@Om@kIe@...,TODO: Add description for each column
45,average_heartrate,float64,150,2,1.04,131.2,TODO: Add description for each column
46,max_heartrate,float64,52,2,1.04,175.0,TODO: Add description for each column
47,gear_id,object,5,2,1.04,g20984891,TODO: Add description for each column
48,workout_type,float64,3,6,3.11,0.0,TODO: Add description for each column
49,average_cadence,float64,63,61,31.61,85.5,TODO: Add description for each column
50,average_watts,float64,114,70,36.27,320.0,TODO: Add description for each column
51,max_watts,float64,95,70,36.27,587.0,TODO: Add description for each column
52,weighted_average_watts,float64,72,70,36.27,369.0,TODO: Add description for each column
53,kilojoules,float64,120,70,36.27,769.9,TODO: Add description for each column
54,device_watts,object,1,70,36.27,True,TODO: Add description for each column
55,location_city,object,0,193,100.00,None,TODO: Add description for each column
56,location_state,object,0,193,100.00,None,TODO: Add description for each column
57,location_country,object,0,193,100.00,None,TODO: Add description for each column

In [10]:
job_config = bigquery.LoadJobConfig(write_disposition='WRITE_TRUNCATE')

full_table_id = f'{PROJECT_ID}.{DATASET_ID}.activities_strava'

client.load_table_from_dataframe(df, full_table_id, job_config=job_config).result()

C:\Users\A200162055\Miniconda3\lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=athlete-dashboard-467718, location=europe-west3, id=a257cc6e-2b75-4b3d-8fa6-8fed477fd856>